### ISSUE TITLE
Improvement Request: A list of improvements

### ISSUE THREAD

**Issue by kaansoral** [naver/egscroll#10]
It would be great to have the improvements listed both as a list in the readme - and - in the code maybe with a special comment like //egsroll - so it would be easy to browse in-code

Since iScroll isn't actively maintained, I'm sure everyone has their own custom/self forks with custom fixes and changes, it would be easier to asses what egscroll actually brings to the table

**Comment by sculove** [comment]
Thank you for your advice. I will apply it.

**Comment by sculove** [comment]
if you want to know custom codes, find `//egscroll`
```js
//egscroll [#issue.no] bla bla
```

**Comment by kaansoral** [comment]
Just checked iscroll.js, it's perfect, thank you, very easy to browse the improvements :)
