### ISSUE TITLE
Can't stop content during animation

### ISSUE THREAD

**Issue by sculove** [naver/egscroll#13]
iScrol couldn't stop animation in some devices

**Comment by kaansoral** [comment]
there was a custom fix for that submitted by someone to iscroll, obviously it wasn't applied to the main project, I saw something similar on egscroll too, clearTimeout's, but I'm not sure they are the same

so basically, I'm mostly making conversation :)

**Comment by sculove** [comment]
@kaansoral this is my fault. ^^ anyway. thank you

**Comment by sculove** [comment]
I fix it.
I apply differenct workaroun.
