### ISSUE TITLE
The click event does not occur in the wrapper elements when called disable() method.

### ISSUE THREAD

**Issue by hiuny** [naver/egscroll#15]
*html*
```html
<div id="wrapper">
    <ul>
        <li>...</li>
        <li>...</li>
        ...
    </ul>
</div>
```

*javascript*
```javascript
var myScroll = new IScroll('#wrapper', {
  click : true
});
myScroll.disable();
$("#wrapper").on("click", function(e){
  console.log("clicked!"); // Do not run.
});
```
Create instance with 'click: true' option.
Call disable() method.
Then.. click event does not occur in wrapper element.
I hope occur click event.

demo : http://codepen.io/chohwihun/pen/Kzvwby

**Comment by sculove** [comment]
I fix it on master branch of iscroll.
you can download bower or npm.
```sh
bower install iscroll#master
```

**Comment by sculove** [comment]
ref. https://github.com/cubiq/iscroll/issues/768
