### ISSUE TITLE
a weird effect when scrolling with iScroll

### ISSUE THREAD

**Issue by sculove** [naver/egscroll#3]
According to issue #760, #441, transitionDuration property is been set to 0.001s in BadAndroid device

- https://github.com/cubiq/iscroll/issues/441
- https://github.com/cubiq/iscroll/issues/760
- https://github.com/cubiq/iscroll/issues/943
- https://github.com/cubiq/iscroll/pull/927

**Comment by sculove** [comment]
this issue is side-effect.
When animation using css3 transition, some android device couldn't stop animation.
therefore, iscroll manages isBadAdroid and sets up transition-duration as `0.001s`

#### solutions
 1. fix isBadAndroid logic. checks following device. 
    - SAMSUNG GalayS2 android 2.3.6
    - chrome browser
    - ...
 2. use other workaround

**Comment by sculove** [comment]
### bad Android TEST
- galaxy S2 is ok 
    - 2.3.6 : `AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1`
    - 4.0.4 : `AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30`

- galaxy S3 is badAndroid (stock brower, webview)
`AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30`
 
- galaxy S4 is badAndroid (stock brower, webview)
`AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30`

- galaxy S5 is OK
`AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Mobile Safari/537.36 (Chrome/)`

- galaxy S6 is OK
`AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Mobile Safari/537.36 (Chrome/)`


galaxy S2 is special device. the Bad Android browser lower than build AppleWebKit/535.19

**Comment by sculove** [comment]
### workaround
- 0.001s is many second. 0.0001ms is enough.
- remove workaround code.

**Comment by kaansoral** [comment]
It's incredible that your testing is this thorough, thank you
